# Generated by Django 4.2.1 on 2023-07-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_menu_icon_alter_menu_target_alter_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
