# Generated by Django 4.2.1 on 2023-07-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_is_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
