# Generated by Django 4.2.1 on 2023-07-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, '文章'), (1, '页面')], default=1, verbose_name='类型'),
        ),
    ]
