# Generated by Django 4.2.1 on 2023-07-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_menu_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='target',
            field=models.CharField(blank=True, choices=[('_self', '默认'), ('_blank', '新窗口打开')], default='_self', max_length=20, null=True),
        ),
    ]
