# Generated by Django 4.2.1 on 2023-07-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_slug_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, '文章'), (1, '页面')], default=0, verbose_name='类型'),
        ),
    ]
