# Generated by Django 4.2.1 on 2023-07-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['parent_id', 'id']},
        ),
    ]
