# Generated by Django 4.2.1 on 2023-07-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_menu_options_menu_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order']},
        ),
    ]
