# Generated by Django 4.2.1 on 2023-07-07 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_post_categories_remove_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='blog.category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(null=True, verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='别名'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, '文章'), (1, '页面')], default=0, verbose_name='类型'),
        ),
    ]
